CREATE TABLE TIPI_CONTATTO_STORICO
(
  ID_EVENTO             NUMBER                  NOT NULL,
  ID_TIPO_CONTATTO      NUMBER                  NOT NULL,
  DESCRIZIONE           VARCHAR2(40 BYTE)       NOT NULL,
  UNICO                 VARCHAR2(2 BYTE)        DEFAULT 'NO'                  NOT NULL,
  IMPORTANZA            NUMBER,
  TIPO_SPEDIZIONE       VARCHAR2(100 BYTE),
  VERSION               NUMBER,
  UTENTE_AGG            VARCHAR2(8 BYTE),
  DATA_AGGIORNAMENTO    DATE,
  DATA                  DATE                    NOT NULL,
  OPERAZIONE            VARCHAR2(2 BYTE),
  BI_RIFERIMENTO        NUMBER,
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE),
  USER_ORACLE           VARCHAR2(30 BYTE),
  INFO                  VARCHAR2(2000 BYTE),
  PROGRAMMA             VARCHAR2(50 BYTE)
)
TABLESPACE AS4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE TIPI_CONTATTO_STORICO IS 'TICS - TIPI CONTATTO STORICO';

COMMENT ON COLUMN TIPI_CONTATTO_STORICO.OPERAZIONE IS 'I=Insert, D=Delete, BI=Before Image, AI=After Image';

COMMENT ON COLUMN TIPI_CONTATTO_STORICO.BI_RIFERIMENTO IS 'id_evento di Before Image di riferimento';



