CREATE TABLE TUTTI_NI_SISTEMARE
(
  NI   NUMBER,
  DAL  DATE
)
TABLESPACE AS4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


