CREATE OR REPLACE FORCE VIEW AS4_V_RECAPITI_CORRENTI
(ID_RECAPITO, NI, DAL, AL, DESCRIZIONE, 
 ID_TIPO_RECAPITO, INDIRIZZO, PROVINCIA, COMUNE, CAP, 
 PRESSO, IMPORTANZA, COMPETENZA, COMPETENZA_ESCLUSIVA, VERSION, 
 UTENTE_AGGIORNAMENTO, DATA_AGGIORNAMENTO)
BEQUEATH DEFINER
AS 
SELECT ID_RECAPITO,
          NI,
          DAL,
          AL,
          DESCRIZIONE,
          ID_TIPO_RECAPITO,
          INDIRIZZO,
          CASE WHEN provincia < 200 THEN provincia ELSE NULL END PROVINCIA,
          TO_NUMBER (
             DECODE (comune, NULL, NULL, provincia || LPAD (comune, 4, 0)))
             COMUNE,
          CAP,
          PRESSO,
          IMPORTANZA,
          COMPETENZA,
          COMPETENZA_ESCLUSIVA,
          VERSION,
          UTENTE_AGGIORNAMENTO,
          DATA_AGGIORNAMENTO
     FROM AS4_RECAPITI
    WHERE TRUNC (SYSDATE) BETWEEN dal AND NVL (al, TO_DATE ('3333333', 'j'));


