CREATE OR REPLACE FORCE VIEW AS4_V_TIPI_CONTATTO
(ID_TIPO_CONTATTO, DESCRIZIONE, UNICO, IMPORTANZA, TIPO_SPEDIZIONE, 
 VERSION, UTENTE_AGGIORNAMENTO, DATA_AGGIORNAMENTO)
BEQUEATH DEFINER
AS 
SELECT "ID_TIPO_CONTATTO",
          "DESCRIZIONE",
          "UNICO",
          "IMPORTANZA",
          "TIPO_SPEDIZIONE",
          "VERSION",
          "UTENTE_AGGIORNAMENTO",
          "DATA_AGGIORNAMENTO"
     FROM as4_tipi_contatto;


