CREATE OR REPLACE FORCE VIEW AS4_V_TIPI_RECAPITO
(ID_TIPO_RECAPITO, DESCRIZIONE, UNICO, IMPORTANZA, VERSION, 
 UTENTE_AGGIORNAMENTO, DATA_AGGIORNAMENTO)
BEQUEATH DEFINER
AS 
SELECT "ID_TIPO_RECAPITO",
          "DESCRIZIONE",
          "UNICO",
          "IMPORTANZA",
          "VERSION",
          "UTENTE_AGGIORNAMENTO",
          "DATA_AGGIORNAMENTO"
     FROM as4_tipi_recapito;


