CREATE OR REPLACE FORCE VIEW AS4_V_CONTATTI
(ID_CONTATTO, ID_RECAPITO, DAL, AL, VALORE, 
 ID_TIPO_CONTATTO, NOTE, IMPORTANZA, COMPETENZA, COMPETENZA_ESCLUSIVA, 
 VERSION, UTENTE_AGGIORNAMENTO, DATA_AGGIORNAMENTO)
BEQUEATH DEFINER
AS 
SELECT "ID_CONTATTO",
          "ID_RECAPITO",
          "DAL",
          "AL",
          "VALORE",
          "ID_TIPO_CONTATTO",
          "NOTE",
          "IMPORTANZA",
          "COMPETENZA",
          "COMPETENZA_ESCLUSIVA",
          "VERSION",
          "UTENTE_AGGIORNAMENTO",
          "DATA_AGGIORNAMENTO"
     FROM as4_contatti;


