CREATE OR REPLACE FORCE VIEW STORICO_SOGGETTI
(NI, DAL, COGNOME, NOME, SESSO, 
 DATA_NAS, PROVINCIA_NAS, COMUNE_NAS, LUOGO_NAS, CODICE_FISCALE, 
 CODICE_FISCALE_ESTERO, PARTITA_IVA, CITTADINANZA, GRUPPO_LING, INDIRIZZO_RES, 
 PROVINCIA_RES, COMUNE_RES, CAP_RES, TEL_RES, FAX_RES, 
 PRESSO, INDIRIZZO_DOM, PROVINCIA_DOM, COMUNE_DOM, CAP_DOM, 
 TEL_DOM, FAX_DOM, INDIRIZZO_WEB, NOTE, UTENTE, 
 DATA_AGG, AL, COMPETENZA, COMPETENZA_ESCLUSIVA, TIPO_SOGGETTO)
BEQUEATH DEFINER
AS 
select ANAGRAFE_SOGGETTI.NI, ANAGRAFE_SOGGETTI.DAL, ANAGRAFE_SOGGETTI.COGNOME,
ANAGRAFE_SOGGETTI.NOME, ANAGRAFE_SOGGETTI.SESSO, ANAGRAFE_SOGGETTI.DATA_NAS,
ANAGRAFE_SOGGETTI.PROVINCIA_NAS, ANAGRAFE_SOGGETTI.COMUNE_NAS,
ANAGRAFE_SOGGETTI.LUOGO_NAS, ANAGRAFE_SOGGETTI.CODICE_FISCALE,
ANAGRAFE_SOGGETTI.CODICE_FISCALE_ESTERO, ANAGRAFE_SOGGETTI.PARTITA_IVA,
ANAGRAFE_SOGGETTI.CITTADINANZA, ANAGRAFE_SOGGETTI.GRUPPO_LING,
ANAGRAFE_SOGGETTI.INDIRIZZO_RES, ANAGRAFE_SOGGETTI.PROVINCIA_RES,
ANAGRAFE_SOGGETTI.COMUNE_RES, ANAGRAFE_SOGGETTI.CAP_RES,
ANAGRAFE_SOGGETTI.TEL_RES, ANAGRAFE_SOGGETTI.FAX_RES, ANAGRAFE_SOGGETTI.PRESSO,
ANAGRAFE_SOGGETTI.INDIRIZZO_DOM, ANAGRAFE_SOGGETTI.PROVINCIA_DOM,
ANAGRAFE_SOGGETTI.COMUNE_DOM, ANAGRAFE_SOGGETTI.CAP_DOM,
ANAGRAFE_SOGGETTI.TEL_DOM, ANAGRAFE_SOGGETTI.FAX_DOM,
ANAGRAFE_SOGGETTI.INDIRIZZO_WEB, ANAGRAFE_SOGGETTI.NOTE,
ANAGRAFE_SOGGETTI.UTENTE, ANAGRAFE_SOGGETTI.DATA_AGG, ANAGRAFE_SOGGETTI.AL,
ANAGRAFE_SOGGETTI.COMPETENZA, ANAGRAFE_SOGGETTI.COMPETENZA_ESCLUSIVA,
ANAGRAFE_SOGGETTI.TIPO_SOGGETTO
from ANAGRAFE_SOGGETTI
where ANAGRAFE_SOGGETTI.AL IS NOT NULL;

COMMENT ON TABLE STORICO_SOGGETTI IS 'Storico Soggetti';



