CREATE INDEX DR$ANST_NOME_CTX$R ON DR$ANST_NOME_CTX$I
(DR$ROWID)
TABLESPACE AS4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


