CREATE UNIQUE INDEX DR$ANAG_NOME_CTX$X ON DR$ANAG_NOME_CTX$I
(DR$TOKEN, DR$TOKEN_TYPE, DR$ROWID)
TABLESPACE AS4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
COMPRESS 2;


