CREATE UNIQUE INDEX IMMA_PK ON IMMAGINI
(ID_IMMAGINE)
TABLESPACE AS4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


