CREATE INDEX RECA_ID_TIPO_RECAPITO_IK ON RECAPITI
(ID_TIPO_RECAPITO)
TABLESPACE AS4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


