CREATE INDEX TICS_IK ON TIPI_CONTATTO_STORICO
(ID_TIPO_CONTATTO)
TABLESPACE AS4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


