CREATE UNIQUE INDEX TICS_PK ON TIPI_CONTATTO_STORICO
(ID_EVENTO)
TABLESPACE AS4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


