CREATE INDEX TIRS_IK ON TIPI_RECAPITO_STORICO
(ID_TIPO_RECAPITO)
TABLESPACE AS4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


