CREATE INDEX TISS_IK ON TIPI_SOGGETTO_STORICO
(TIPO_SOGGETTO)
TABLESPACE AS4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


