ALTER TABLE ANAGRAFICI_STORICO ADD (
  CONSTRAINT ANAS_OPERAZIONE_CK
  CHECK (operazione in ('I','D','BI','AI'))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFICI_STORICO ADD (
  CONSTRAINT ANAS_PK
  PRIMARY KEY
  (ID_EVENTO)
  USING INDEX ANAS_PK
  ENABLE VALIDATE);

