ALTER TABLE ANAGRAFE_SOGGETTI_TABLE ADD (
  CONSTRAINT ANAG_SOGG_TAB_CAP_DOM_CC
  CHECK (
   CAP_DOM is null or (CAP_DOM between '0' and '99999'
   ))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_SOGGETTI_TABLE ADD (
  CONSTRAINT ANAG_SOGG_TAB_CAP_RES_CC
  CHECK (
   CAP_RES is null or (CAP_RES between '0' and '99999'
   ))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_SOGGETTI_TABLE ADD (
  CONSTRAINT ANAG_SOGG_TAB_COMPETENZA_ES_CC
  CHECK (
   COMPETENZA_ESCLUSIVA is null or (COMPETENZA_ESCLUSIVA in ('E','P')))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_SOGGETTI_TABLE ADD (
  CONSTRAINT ANAG_SOGG_TAB_COMUNE_DOM_CC
  CHECK (
   COMUNE_DOM is null or (COMUNE_DOM between 0 and 999
   ))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_SOGGETTI_TABLE ADD (
  CONSTRAINT ANAG_SOGG_TAB_COMUNE_NAS_CC
  CHECK (
   COMUNE_NAS is null or (COMUNE_NAS between 0 and 999
   ))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_SOGGETTI_TABLE ADD (
  CONSTRAINT ANAG_SOGG_TAB_NI_CC
  CHECK (
   NI >= 0)
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_SOGGETTI_TABLE ADD (
  CONSTRAINT ANAG_SOGG_TAB_PROVINCIA_DOM_CC
  CHECK (
   PROVINCIA_DOM is null or (PROVINCIA_DOM between 0 and 999
   ))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_SOGGETTI_TABLE ADD (
  CONSTRAINT ANAG_SOGG_TAB_PROVINCIA_NAS_CC
  CHECK (
   PROVINCIA_NAS is null or (PROVINCIA_NAS between 0 and 999
   ))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_SOGGETTI_TABLE ADD (
  CONSTRAINT ANAG_SOGG_TAB_SESSO_CC
  CHECK (
   SESSO is null or (SESSO in ('F','M')))
  ENABLE VALIDATE);

ALTER TABLE ANAGRAFE_SOGGETTI_TABLE ADD (
  CONSTRAINT ANST_PK
  PRIMARY KEY
  (NI, DAL)
  USING INDEX ANST_PK
  ENABLE VALIDATE);

