ALTER TABLE CONTATTI_STORICO ADD (
  CONSTRAINT CONS_OPERAZIONE_CK
  CHECK (operazione in ('I','D','BI','AI'))
  ENABLE VALIDATE);

ALTER TABLE CONTATTI_STORICO ADD (
  CONSTRAINT CONS_PK
  PRIMARY KEY
  (ID_EVENTO)
  USING INDEX CONS_PK
  ENABLE VALIDATE);

