ALTER TABLE CONTATTI ADD (
  CONSTRAINT CONTATTI_COMPETENZA_ES_CC
  CHECK (COMPETENZA_ESCLUSIVA is null or ( COMPETENZA_ESCLUSIVA in ('E','P') ))
  ENABLE VALIDATE);

ALTER TABLE CONTATTI ADD (
  CONSTRAINT CONT_PK
  PRIMARY KEY
  (ID_CONTATTO)
  USING INDEX CONT_PK
  ENABLE VALIDATE);

