ALTER TABLE RECAPITI ADD (
  CONSTRAINT RECAPITI_CAP_CC
  CHECK (CAP is null or (CAP between '0' and '99999' ))
  ENABLE VALIDATE);

ALTER TABLE RECAPITI ADD (
  CONSTRAINT RECAPITI_COMPETENZA_ES_CC
  CHECK (COMPETENZA_ESCLUSIVA is null or ( COMPETENZA_ESCLUSIVA in ('E','P') ))
  ENABLE VALIDATE);

ALTER TABLE RECAPITI ADD (
  CONSTRAINT RECAPITI_NI_CC
  CHECK (NI >= 0)
  ENABLE VALIDATE);

ALTER TABLE RECAPITI ADD (
  CONSTRAINT RECAPITI_PROVINCIA_CC
  CHECK (PROVINCIA is null or (PROVINCIA between 0 and 999 ))
  ENABLE VALIDATE);

ALTER TABLE RECAPITI ADD (
  CONSTRAINT RECAPITI_PK
  PRIMARY KEY
  (ID_RECAPITO)
  USING INDEX RECAPITI_PK
  ENABLE VALIDATE);

