ALTER TABLE RECAPITI_STORICO ADD (
  CONSTRAINT RECS_OPERAZIONE_CK
  CHECK (operazione in ('I','D','BI','AI'))
  ENABLE VALIDATE);

ALTER TABLE RECAPITI_STORICO ADD (
  CONSTRAINT RECS_PK
  PRIMARY KEY
  (ID_EVENTO)
  USING INDEX RECS_PK
  ENABLE VALIDATE);

