ALTER TABLE TIPI_RECAPITO ADD (
  CONSTRAINT TIPI_RECA_PK
  PRIMARY KEY
  (ID_TIPO_RECAPITO)
  USING INDEX TIPI_RECA_PK
  ENABLE VALIDATE);

ALTER TABLE TIPI_RECAPITO ADD (
  CONSTRAINT TIRE_DESCRIZIONE_UK
  UNIQUE (DESCRIZIONE)
  USING INDEX TIRE_DESC_IK
  ENABLE VALIDATE);

