ALTER TABLE TIPI_CONTATTO_STORICO ADD (
  CONSTRAINT TICS_OPERAZIONE_CK
  CHECK (operazione in ('I','D','BI','AI'))
  ENABLE VALIDATE);

ALTER TABLE TIPI_CONTATTO_STORICO ADD (
  CONSTRAINT TICS_PK
  PRIMARY KEY
  (ID_EVENTO)
  USING INDEX TICS_PK
  ENABLE VALIDATE);

