ALTER TABLE TIPI_SOGGETTO_STORICO ADD (
  CONSTRAINT TISS_OPERAZIONE_CK
  CHECK (operazione in ('I','D','BI','AI'))
  ENABLE VALIDATE);

ALTER TABLE TIPI_SOGGETTO_STORICO ADD (
  CONSTRAINT TISS_PK
  PRIMARY KEY
  (ID_EVENTO)
  USING INDEX TISS_PK
  ENABLE VALIDATE);

