ALTER TABLE TIPI_RECAPITO_STORICO ADD (
  CONSTRAINT TIRS_OPERAZIONE_CK
  CHECK (operazione in ('I','D','BI','AI'))
  ENABLE VALIDATE);

ALTER TABLE TIPI_RECAPITO_STORICO ADD (
  CONSTRAINT TIRS_PK
  PRIMARY KEY
  (ID_EVENTO)
  USING INDEX TIRS_PK
  ENABLE VALIDATE);

