ALTER TABLE TIPI_CONTATTO ADD (
  CONSTRAINT TICO_SPED_CC
  CHECK (tipo_spedizione in ('MAIL','FAX','SMS'))
  ENABLE VALIDATE);

ALTER TABLE TIPI_CONTATTO ADD (
  CONSTRAINT TICO_PK
  PRIMARY KEY
  (ID_TIPO_CONTATTO)
  USING INDEX TICO_PK
  ENABLE VALIDATE);

ALTER TABLE TIPI_CONTATTO ADD (
  CONSTRAINT TICO_DESCRIZIONE_UK
  UNIQUE (DESCRIZIONE)
  USING INDEX TICO_DESC_IK
  ENABLE VALIDATE);

