ALTER TABLE TIPI_SOGGETTO ADD (
  CONSTRAINT TISO_CATEGORIA_TIPO_SOGG_CC
  CHECK (CATEGORIA_TIPO_SOGGETTO in ('PF','PG'))
  ENABLE VALIDATE);

ALTER TABLE TIPI_SOGGETTO ADD (
  CONSTRAINT TISO_PK
  PRIMARY KEY
  (TIPO_SOGGETTO)
  USING INDEX TISO_PK
  ENABLE VALIDATE);

